// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../resource';

export class Shared extends APIResource {}

/**
 * This object provide you additional information about errors encountered while
 * performing the operation
 */
export interface Error {
  /**
   * An API specific code representing the type of error.
   */
  code: string;

  /**
   * The HTTP status code generated by the origin server for this occurrence of the
   * error.
   */
  status: number;

  /**
   * A short, human-readable summary of the error type.
   */
  title: string;

  /**
   * A (best effort) human readable explanation specific to this occurrence of the
   * error.
   */
  detail?: string;
}

/**
 * Error response
 */
export interface ErrorResponse {
  /**
   * This object provide you additional information about errors encountered while
   * performing the operation
   */
  error: Error;
}

/**
 * The list of events to enable for this webhook
 */
export type WebhookEventType =
  | 'email.sent'
  | 'email.delivered'
  | 'email.opened'
  | 'email.clicked'
  | 'email.bounced'
  | 'email.complained'
  | 'email.rejected'
  | 'email.delivery_delayed';

export declare namespace Shared {
  export {
    type Error as Error,
    type ErrorResponse as ErrorResponse,
    type WebhookEventType as WebhookEventType,
  };
}
