configured_endpoints: 35
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bazoud-corp%2Fnuntly-ab481795a4e3e48639dd34e9db6910a0d8344d85d66021d2ecb9cf4b734dfbb4.yml
openapi_spec_hash: c0f38da51eeeed306bfaca23b60f5c15
config_hash: 2e7658baca40c97d8d3ddecbb87b08ea
